### ISSUE TITLE
The Scale of pose

### ISSUE THREAD

**Issue by chenlongwhu** [Sungmin-Woo/ProDepth#4]
Hello, Thank you for your excellent work. I want to know why 
```
pose = 0.01 * out.view(-1, 6)
```
what does this code mean? pose[..., :3] is the predicted rotation, pose[...,3:] is the predicted translation. Reducing the translation can control the scope of the depth map, but why reduce the rotation angle?

**Comment by Sungmin-Woo** [comment]
Hi @chenlongwhu,

The 0.01 scaling is originated from the implementation of MonoDepth2. This scaling factor aids in stabilizing the initial training phase, but it does not seem to be very important overall.  Please see [monodepth2#260](https://github.com/nianticlabs/monodepth2/issues/260).

I hope this helps :)

**Comment by chenlongwhu** [comment]
> Hi @chenlongwhu,
> 
> The 0.01 scaling is originated from the implementation of MonoDepth2. This scaling factor aids in stabilizing the initial training phase, but it does not seem to be very important overall. Please see [monodepth2#260](https://github.com/nianticlabs/monodepth2/issues/260).
> 
> I hope this helps :)

I got it! Thank you for your reply.
