### ISSUE TITLE
For reproducing the code effect

### ISSUE THREAD

**Issue by ghost** [Sungmin-Woo/ProDepth#6]
Thank you for your excellent work. However, we ran into an issue during reproduction. The best result we obtained from the code is: Abs Rel: 0.094, δ < 1.25: 0.902. Could you kindly assist with this? Looking forward to hearing back from you.

**Comment by Sungmin-Woo** [comment]
The original code contained some errors, and the updated code with necessary modifications has now been re-uploaded. Sorry for the late response and thank you for your patience!
