### ISSUE TITLE
The reproduce results on Cityscapes dataset

### ISSUE THREAD

**Issue by fufj** [Sungmin-Woo/ProDepth#7]
Thanks for your remarkable work. 
I met a issue when I test the performance of re-trained model on Cityscapes dataset. I just took all default settings in readme.txt to train our model, but got following metrics:
-> Evaluating
   Mono evaluation - using median scaling
100%|██████████████████████████████████████████████████████████████████████| 1525/1525 [00:27<00:00, 56.32it/s]
 MULTI Scaling ratios | med: nan | std: nan

   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&     nan  &     nan  &     nan  &     nan  &   0.259  &   0.507  &   0.722  \\

Hope you can give some advice.

**Comment by Sungmin-Woo** [comment]
The original code contained some errors, and the updated code with necessary modifications has now been re-uploaded. Sorry for the late response and thank you for your patience!

**Comment by fufj** [comment]
> The original code contained some errors, and the updated code with necessary modifications has now been re-uploaded. Sorry for the late response and thank you for your patience!

Thank you for your help.
But it still cannot work. I got the same wrong results when I use the updated files. Would you mind provding additional suggestions when  we test our model on the Cityscapes dataset?
Best wishes!

**Comment by Sungmin-Woo** [comment]
Have you checked whether the issue comes from the trained model itself or from the evaluation metric calculation? You can monitor the training progress using TensorBoard or visualize the output with test images.

**Comment by 757787182** [comment]
> > 原始代码包含一些错误，经过必要修改的更新代码现已重新上传。很抱歉回复晚了，感谢您的耐心等待！
> 
> 感谢您的帮助。但它仍然不起作用。当我使用更新的文件时，我得到了相同的错误结果。当我们在 Cityscapes 数据集上测试我们的模型时，您是否介意提供其他建议？ 愿你安好！



> > 原始代码包含一些错误，经过必要修改的更新代码现已重新上传。很抱歉回复晚了，感谢您的耐心等待！
> 
> 感谢您的帮助。但它仍然不起作用。当我使用更新的文件时，我得到了相同的错误结果。当我们在 Cityscapes 数据集上测试我们的模型时，您是否介意提供其他建议？ 愿你安好！



> > 原始代码包含一些错误，经过必要修改的更新代码现已重新上传。很抱歉回复晚了，感谢您的耐心等待！
> 
> 感谢您的帮助。但它仍然不起作用。当我使用更新的文件时，我得到了相同的错误结果。当我们在 Cityscapes 数据集上测试我们的模型时，您是否介意提供其他建议？ 愿你安好！

Hello! Have you tested the results provided by the probdepth model? Can the results be made public?

**Comment by aqzhang218** [comment]
> > The original code contained some errors, and the updated code with necessary modifications has now been re-uploaded. Sorry for the late response and thank you for your patience!
> 
> Thank you for your help. But it still cannot work. I got the same wrong results when I use the updated files. Would you mind provding additional suggestions when we test our model on the Cityscapes dataset? Best wishes!

I also encountered this problem. Have you solved this problem?
